### ISSUE TITLE
Multidomain capability (feature request)

### ISSUE THREAD

**Issue by DonChef660** [brotkrueml/typo3-matomo-widgets#1]
Would be nice to have the option to set _general.url, general.idSite, general.tokenAuth_ per Widget or Site, to ensure multidomain capability.

**Comment by brotkrueml** [comment]
Yes, I also thought about it. I decided to start simple to gather feedback like yours instead of developing a highly sophisticated solution in many months ;-)

Set the case, the settings for a Matomo installation is set in the sites configuration for every site independently:
- The configuration of the widgets is done in Services.yaml and Services.php. The Services.[php|yaml] is only executed once during compilation of the injection container when building the caches. If the site configuration is available at this early time I have to check.
- For each site configuration a widget has to be created. In theory, this could be done in the Services.yaml programmatically iterating over the site configurations which have Matomo settings. So if you have e.g. 3 site configurations, each widget has to be defined 3 times, for each site configuration once. Then the access rights could be granted for specific user groups according to a site configuration.
- There can then be quite a lot overhead: When there are 20 reports given, 60 widgets are available to choose from. But that can be dealt with, I think.

Perhaps in a future version of TYPO3 a widget might be configurable when adding it to a dashboard (that would be a dream, e.g. also for RSS feeds). Then it could also be possible to select a Matomo installation from the widget configuration modal. Then only some permission check has to be added, so only allowed Matomo installations can be selected by that user(group).

What do you think? Can you imagine another approach which I have overlooked?

**Comment by DonChef660** [comment]
I understand. With the currently available widget features it seems rather hard to handle this implementation without having to deal with other problems.
A configurable widget would of course be the best solutions, for other use cases too.
As a temporary solution the 2nd seems okay, but i cant really say if the effort would be too big.

thanks for the extension nonetheless!

**Comment by brotkrueml** [comment]
**Idea:**

In ``config/matomo_widgets/matomo_installations.php`` is the configuration for different Matomo installation:

    return [
        0 => [
            'name' => 'Example',
            'baseUrl' => 'https://example.org/',
            'siteId' => 42,
            'tokenAuth' => '',
            'activatedWidgets' => [
                // ... list of wanted widgets for this installation
            ],
        ],
        // ... other installations
    ]

This can be read in a ``Configuration/Services.php`` and the widgets configured in a loop, for each Matomo installation independently.

A backend module under ``Site Management`` can be used to configure the Matomo installations in the GUI (ordinary TCA records). When changing, adding, deleting an installation, the ``config/matomo_widgets/matomo_installations.php`` file is adjusted automatically via DataHandler hook. Afterwards the cache must be flushed in Admin Tools > Maintenance.

The widgets have the Matomo installation name in the title, so they can be differentiated. Each widget for each Matomo installation can be assigned different backend groups.

Have to try out if it works that way or has some drawbacks.

Some sugar: Perhaps for each Matomo installation a Dashboard preset can be created.

**Comment by brotkrueml** [comment]
**Another idea:**
Configure the Matomo settings (URL, site id, auth token) for each site in the Sites Configuration module. The yaml file of the configurations can then be read in the Services.php and the Matomo installations identified. Then all widgets will be registered for each given Matomo installation. The authorisation token can be placed in an environment variable so it is not versioned.

Additionally, it could be possible to select the available Matomo widgets for each site.

Advantage: The Matomo settings and the widgets configuration are both stored in a versioning system.

For now, this is my favourite implementation.
