### ISSUE TITLE
TYPO3 Exception when adding a widget without configuration

### ISSUE THREAD

**Issue by spoonerWeb** [brotkrueml/typo3-matomo-widgets#2]
When I want to add a matomo widget, this exception appears:

![Matomo Widget Exception](https://user-images.githubusercontent.com/1793083/86886473-45e03c80-c0f7-11ea-81ef-4b3830bc9e51.jpg)

After that the dashboard isn't accessible anymore, the exception always appears.
Only removing the dashboard record in list view helps.
But when adding a matomo widget again, breaks it again.

Using TYPO3 CMS 10.4.5 and Extension version 0.1.0

**Comment by brotkrueml** [comment]
Yes, this will be fixed in the next version. The configuration is missing, so this exception is thrown.

Just fill out the extension configuration. The extension has to know, where your Matomo installation is and your site id and authorisation token:
https://docs.typo3.org/p/brotkrueml/typo3-matomo-widgets/0.1/en-us/Configuration/Index.html
