### ISSUE TITLE
No Matomo Widget in Dashboard in classic TYPO3 installation

### ISSUE THREAD

**Issue by GenerationU** [brotkrueml/typo3-matomo-widgets#5]
Typo3 Version 10.4.6 and 10.4.11
Hey, i have no Widget in Dashboard. And after do the settings in the sitesconfig too.
I tested first in 0.3. Then in 0.2. Both the same. FOr a few Weeks it did working at version 0.2.
I think it have maybe something to do with a Matomoupdate and the authcode? I mean maybe now some settings are importand in Matomo now. But if, i cant find out.
Thanks, i hope it will works. Very simple-nice Extension.

**Comment by PhilippKuhlmay** [comment]
@GenerationU Can you also tell us, which Matomo Version you have? I see there is a new major version 4.x

**Comment by PhilippKuhlmay** [comment]
I tested it with TYPO3 10.4.6, 10.4.11 and 10.4.12.
I installed matomo_widgets 0.2 and 0.3.1
I tested it with my Matomo Installation in both versions 3.x and the new version 4.1.0.
For me it worked with all versions without any issues.
It still works if I set a wrong Auth-Code. The widgets doesn't show any data because of the wrong AuthCode but I can still select any widgets and dashboard presets.

**Comment by brotkrueml** [comment]
@GenerationU Did you made an upgrade from version 0.2 to 0.3 or a new installation? If upgrade, have you executed all upgrade wizards? There are three of them. The first is the migration from extension configuration to site configuration. If that was successful, two other wizards are visible to migrate the dashboard widgets and the access rights of the widgets to the new configuration. I assume you have only one site configuration?

Documentation for the migration: https://docs.typo3.org/p/brotkrueml/typo3-matomo-widgets/0.3/en-us/Migration/Index.html

If you have more than one site configuration the case is a little bit trickier, because you cannot execute the wizard for the site configuration. Then move the configuration from extension to site manually (important: only one site should be configured) and then you should see also the two migration wizards for dashboard and access rights. After executing them, you can configure other sites for Matomo usage.

The Matomo version should not matter: I upgraded three weeks ago from 3.x to 4.1 and everything worked in the dashboard. There were no breaking changes in Matomo that affects the dashboard widgets.

If you have still problems I can offer to look with you on your installation. Perhaps there is a glitch I haven't considered.

**Comment by GenerationU** [comment]
> I tested it with TYPO3 10.4.6, 10.4.11 and 10.4.12.
> I installed matomo_widgets 0.2 and 0.3.1
> I tested it with my Matomo Installation in both versions 3.x and the new version 4.1.0.
> For me it worked with all versions without any issues.
> It still works if I set a wrong Auth-Code. The widgets doesn't show any data because of the wrong AuthCode but I can still select any widgets and dashboard presets.

Its Matomo 4.0.5 . The Update about the Matomo Updatebutton failed last time, Matomo said. Something with wrong link or something. Maybe it tryed to update on 4.1. Maybe is the problem im working on a, how i have to call it, System Domain from Server? stats.servername.de I have no idea how Typo3 Ext do connect with Matomo :D

Three Possibllitys now:
1) Matomo widget ext. shows only the widget if it can connected with Matomo. Only connected, not importand if the AUthcode is write.
2) Something went wrong in Typo
Or it have something to do with the webserver
Im a Nub. Maybe something else...

**Comment by brotkrueml** [comment]
The extension uses the Reporting API: https://developer.matomo.org/api-reference/reporting-api, which is just like a REST API which is called for each widget.

Is in your site configuration the Matomo settings available?

You can check the API manually, example:
https://demo.matomo.cloud/?module=API&method=DevicesDetection.getBrowsers&idSite=1&period=day&date=yesterday&format=JSON&token_auth=anonymous

Replace "demo.matomo.cloud" with your server name, "idSite" with your site id and "token_auth" with your authorization token.

Have you cleared the cache via "Admin Tools > Maintenance"? As the dashboard widgets are configured with dependency injection the cache must be flushed in this module.

**Comment by GenerationU** [comment]
@brotkrueml brotkrueml I made both. Thats the reason why i know. that it dont working in an 0.2.

Yes, i have no idea. That i dont steel your time so much,(its possiible that i made a very stupid fail :D) you can tell me what i have to get before you look? I Wrote you an Email

**Comment by brotkrueml** [comment]
@GenerationU Please check if the API works manually in your browser. This verifies that the credentials are correct.

**Comment by brotkrueml** [comment]
Okay, the API works. After looking on the system we discovered, that the widgets are not available in the dependeny injection cache. It is a classic TYPO3 installation (TYPO3 10.4.6, PHP 7.3).

Have to check it locally on a classic installtion.

**Comment by brotkrueml** [comment]
Okay, found it: I am reading the yaml of the site configuration manually, because at this time no configuration object is available. In the classic installation the config path is different. I plan to provide a new extension version in the next days. The next extension version will require at least TYPO3 v10.4.11 because it depends on another feature which was introduced in this particular TYPO3 version. However, v10.4.11 is a security release, so it should be installed anyway.

**Comment by GenerationU** [comment]
Oh nice, thanks for the solution. Waiting a few days then :). Updated already.
